---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: cisco
  pre_tasks:
    - include_vars:
        file: 'vault.yml'
  #no_log: true
  connection: network_cli
  gather_facts: no
  vars:
    gitpush_repo_path: /tmp/demo-router-configs/.git/
    become: false
    gitpush_user: ansible
    notify: null
    router_backup_dir: backup 
    git_remote_repo_path: 'git@github.com:sheeshkebab/demo-router-configs.git' 
    git_checkout_location: /tmp/demo-router-configs
    tower_job_template_id: 0 

  tasks:

    - name: Add the PRIVATE KEY used for github authentication to ssh-agent
      local_action:
        module: shell
        _raw_params: "command echo \"{{ private_key_content }}\" | ssh-add -"
      when: tower_job_template_id > 0 

    # ive used id_rsa below because it gets used by default.
    # Otherwise we would also need to define an ssh config file for locating the right key to use.
    - name: Deploy github private key
      copy:
        content: "{{private_key_content}}"
        dest: "~/.ssh/id_rsa"
        owner: awx 
        group: awx 
        mode: 0600
      no_log: true
      when: tower_job_template_id > 0

    - name: Test the PRIVATE KEY can give us access to github 
      local_action: shell ssh -i ~/.ssh/git-hub -T git@github.com
      ignore_errors: true
      register: github_access_ssh

    - name: Import Role - GitPull
      import_role: 
        name: ansible-gitpull-deploy

#    - name: Debug ssh access
#      debug:
#        msg: "{{ github_access_ssh }}"

    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
        #backup_options:
        #  filename: backup.cfg
        #  dir_path: "./{{router_backup_dir}}"
      register: config_output

    - name: RENAME BACKUP
      copy:
        src: "{{config_output.backup_path}}"
        dest: "./{{router_backup_dir}}/{{inventory_hostname}}.config"

    - name: REMOVE NON CONFIG LINES
      lineinfile:
        path: "./{{router_backup_dir}}/{{inventory_hostname}}.config"
        line: "Building configuration..."
        state: absent

    - name: REMOVE NON CONFIG LINES - REGEXP
      lineinfile:
        path: "./{{router_backup_dir}}/{{inventory_hostname}}.config"
        regexp: 'Current configuration.*'
        state: absent  

    - name: ADD BACKUP TO LOCAL VERSION CONTROL
      copy:
        src: "./{{router_backup_dir}}/{{inventory_hostname}}.config" 
        dest: "{{ git_checkout_location }}"

- name: Push the contents back up into the remote repo
  hosts: cisco 
  gather_facts: no
  vars:
    gitpush_repo_path: /tmp/demo-router-configs/.git
    become: false
    gitpush_user: ansible
    notify: null
    git_checkout_location: /tmp/iag-configs
    git_remote_repo_path: 'git@github.com:sheeshkebab/iag-configs.git'

  roles:
    - role: ansible-gitpush-deploy
