---
- name: BACKUP and RESTORE CONFIGURATION
  hosts: cisco
  connection: network_cli
  gather_facts: no

  vars:
    router_backup_dir: backup 
    become: false
    gitpush_user: ansible
    notify: null
    git_checkout_location: backup 
    git_remote_repo_path: 'git@github.com:sheeshkebab/demo-router-configs.git'

  roles:
    - role: ansible-gitpull-deploy


  tasks:

    - block:
      - name: BACKUP THE CONFIG
        ios_config:
          backup: yes
          #backup_options:
          #  filename: backup.cfg
          #  dir_path: "./{{router_backup_dir}}"
        register: config_output

      - name: RENAME BACKUP
        copy:
          src: "{{config_output.backup_path}}"
          #dest: "./{{router_backup_dir}}/{{inventory_hostname}}.config"
          dest: "./{{router_backup_dir}}/{{inventory_hostname}}.config"

      - name: REMOVE NON CONFIG LINES
        lineinfile:
          path: "./{{router_backup_dir}}/{{inventory_hostname}}.config"
          line: "Building configuration..."
          state: absent

      - name: REMOVE NON CONFIG LINES - REGEXP
        lineinfile:
          path: "./{{router_backup_dir}}/{{inventory_hostname}}.config"
          regexp: 'Current configuration.*'
          state: absent

      when: whattodo == 'backup'
    
    - block:
      - name: Gather facts (ios)
        ios_facts:
        when: ansible_network_os == 'ios'
  
      - name: debug inventory hostname
          var: "{{ hostvars[inventory_hostname] }}" 

      - name: Setting fact with inventory hostname so we can ssh on the new config
        set_fact:
          #dest_host: "{{ hostvars[inventory_hostname].ansible_host }}" 
          dest_host: "{{ hostvars[inventory_hostname] }}" 

      - name: COPY RUNNING CONFIG TO ROUTER
        command: scp ./backup/{{inventory_hostname}}.config {{dest_host}}:/{{inventory_hostname}}.config

      - name: CONFIG REPLACE
        ios_command:
          commands:
            - config replace flash:{{inventory_hostname}}.config force

      when: whattodo == 'restore'
